ROWS: 5000
COLUMNS:
  - IDX: 01
    Name: id
    DataType: int
    Function: sequence
  - IDX: 02
    Name: payer
    DataType: string
    Function: template
    Parameters:
      - key: name
        value: RandomUserID
      - key: content
        value: "payer{{.GenerateData}}"
      - key: min
        value: 1
      - key: max
        value: 10
      - key: format
        value: "%08d"
  - IDX: 03
    Name: receiver
    DataType: string
    Function: template
    Parameters:
      - key: name
        value: RandomUserID
      - key: content
        value: "user{{.GenerateData}}"
      - key: min
        value: 1
      - key: max
        value: 1000
      - key: format
        value: "%010d"
  - IDX: 04
    Name: amount
    DataType: int
    Function: random
    Max: 10000
    Min: 1
  - IDX: 05
    Name: payment_uuid
    DataType: string
    Function: uuid
  - IDX: 06
    Name: payment_type
    DataType: string
    Function: list
    Values: 
    - international
    - national
    - others
  - IDX: 07
    Name: payment_date
    DataType: Date
    Function: RandomDate
    Parameters:
      - key: min
        value: 2022-01-01
      - key: max
        value: 2022-06-01
  - IDX: 08
    Name: user_id
    DataType: string
    Function: RandomString
    Parameters:
      - key: min
        value: 6
      - key: max
        value: 8
  - IDX: 09
    Name: access_content
    DataType: json
    Function: Template
    Parameters:
      - key: content
        value: '{"access_type": "{{$BROWSER}}", "ip_address": "{{$IPADDR}}"}'
