ROWS: 5000
COLUMNS:
  - 
    IDX: 01
    Name: id
    DataType: int
    Function: sequence
  -
    IDX: 02
    Name: payer
    DataType: string
    Function: template
    Parameters:
      - key: name
        value: RandomUserID
      - key: content
        value: "payer{{.GenerateData}}"
      - key: min
        value: 1
      - key: max
        value: 10
      - key: format
        value: "%08d"
  -
    IDX: 03
    Name: receiver
    DataType: string
    Function: template
    Parameters:
      - key: name
        value: RandomUserID
      - key: content
        value: "user{{.GenerateData}}"
      - key: min
        value: 1
      - key: max
        value: 1000
      - key: format
        value: "%010d"
  -
    IDX: 04
    Name: amount
    DataType: int
    Function: random
    Max: 10000
    Min: 1
